---
title: "Analytical Hierarchy Process Arthur WEHBE"
author: "Arthur WEHBE"
date: "2024-04-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

normalize_and_average <- function(mat) {


sumn_cols <- colSums(mat)


for (col in 1:3) {
  mat[, col] <- mat[, col] / sumn_cols[col]
}

return(matrix(rowMeans(mat), ncol = 1))
  
}

my.AHP <- function(list_matrix,criteria){
  
  col_Price <- normalize_and_average(list_matrix[[1]])
  
  col_Gear <- normalize_and_average(list_matrix[[2]])
  
  col_weight_durability <- normalize_and_average(list_matrix[[3]])


criterion_matrix <- matrix(c(col_Price, col_Gear, col_weight_durability), nrow = 3, byrow = FALSE)

criteria_norm_avg <- normalize_and_average(criteria)

criterion <- criterion_matrix %*% criteria_norm_avg
names(criterion) <- rownames(criteria)

ranking <- order(criterion, decreasing = TRUE)
cat("The order is :",ranking)
cat("\n")

l <- list()

for (i in ranking) {
  l <- append(l, round(criterion[i], 4))
}
cat("\n")

print(l)

cat("\n")

Cons_Criteria  <- criteria %*% criteria_norm_avg

Cons_Price <- list_matrix[[1]] %*% col_Price

Cons_Gear <- list_matrix[[2]] %*% col_Gear

Cons_weight_durability  <- list_matrix[[3]] %*% col_weight_durability

CR_Criteria <- (((sum(Cons_Criteria/criteria_norm_avg)/3)-3)/2)/0.58

CR_Criteria <- round(CR_Criteria, 4)

CR_Price <- (((sum(Cons_Price/col_Price)/3)-3)/2)/0.58

CR_Price <- round(CR_Price, 4)

CR_Gear <- (((sum(Cons_Gear/col_Gear)/3)-3)/2)/0.58

CR_Gear <- round(CR_Gear, 4)

CR_weight_durability <- (((sum(Cons_weight_durability/col_weight_durability)/3)-3)/2)/0.58

CR_weight_durability <- round(CR_weight_durability, 4)

print(paste("Price matrix consistency ratio : ",CR_Price))

cat("\n")

print(paste("Gear matrix consistency ratio : ",CR_Gear))

cat("\n")

print(paste("Weight/Durability matrix consistency ratio : ",CR_weight_durability))

cat("\n")

print(paste("Criteria matrix consistency ratio : ",CR_Criteria))

cat("\n")

cat("The final ranking of the bikes is: \nFirst: the Xandu Mark III, \nSecond: the Zodiak MB5, and \nThird: the Yellow Hawk Z9\n")

cat("Grace can trust the overall ranking since the consistency ratio is equal or near 0 : \n\n")


cat("Consistency Ratio Price:", CR_Price, "\n\n")

cat("Consistency Ratio Gear:", CR_Gear, "\n\n")

cat("Consistency Ratio weight/durability:", CR_weight_durability, "\n\n")

cat("Consistency Ratio Criteria:", CR_Criteria, "\n\n")


}
  


Price <- matrix(c(1,3,6,
                  1/3,1,2,
                  1/6,0.5,1),
                  nrow = 3, byrow = TRUE)

Gear <- matrix(c(1,1/3,1/7,
                      3,1,1/4,
                      7,4,1),
                          nrow = 3, byrow = TRUE)
weight_durability <- matrix(c(1,3,1,
                              1/3,1,0.5,
                              1,2,1),
                              nrow = 3, byrow = TRUE)

liste_mats <- list(Price, Gear, weight_durability)

mat <- matrix(c(1,3,5,
                1/3,1,2,
                1/5,0.5,1),
                nrow = 3, byrow = TRUE)

rownames(mat) <- c("Xandu Mark III", "Yellow Hawk Z9", "Zodiak MB5")

my.AHP(liste_mats, mat)

```

